# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='arbum_title',
            new_name='album_title',
        ),
    ]
